- appgate/appgate.py
- appgate/client.py
- appgate/state.py
Trying to see what's going on on #58
> Sync current and latest generation after plan is applied

- appgate/appgate.py
> Print errors produced when applying plan anf exit in case of errors

- appgate/appgate.py
- appgate/state.py
> Fix the stacktrace when logging

- README.org
- appgate/__main__.py
- appgate/appgate.py
- appgate/client.py
- appgate/types.py
This option can be useful when testing the operator in environments with self signed certificates.
> Adds option to skip SSL cert verification

- appgate/appgate.py
It was not working. When it was passed the certificate was checked anyway.
> Fix `--no-verify` flag.

- appgate/appgate.py
We are expecting a PEM file, so we don't need to decode it, just save it
> Fix bug when saving certificate from env variable

- .github/workflows/docker.yml
- .github/workflows/python.yml
- The python workflow will run only on PRs
> Add workflow to create the images and to push them into gcr

- appgate/appgate.py
- appgate/state.py
Never return an modified entity unless all the dependencies are resolved.
> Fix bug when resolvinf only some of the dependencies

- .github/workflows/python.yml
- appgate/__main__.py
- appgate/appgate.py
- appgate/attrs.py
- appgate/bytes.py
- appgate/client.py
- appgate/customloaders.py
- appgate/logger.py
- appgate/openapi/attribmaker.py
- appgate/openapi/openapi.py
- appgate/openapi/parser.py
- appgate/openapi/types.py
- appgate/openapi/utils.py
- appgate/secrets.py
- appgate/state.py
- appgate/types.py
- requirements-build.txt
- tests/test_appgatesecrets.py
- tests/test_entities.py
- tests/test_state.py
- tests/utils.py
Added as part of the existing python build.
> Format sdp-operator using black and enforce it in CI

- .github/workflows/docker.yml
Dont use environments for the docker github actions
> Fix and improve docker actions

- Makefile
- appgate/appgate.py
- appgate/attrs.py
- appgate/bytes.py
- appgate/client.py
- appgate/openapi/parser.py
- appgate/openapi/utils.py
- appgate/state.py
- appgate/types.py
- mypy.ini
- requirements-build.txt
> Bump mypy to version 0.930

- Makefile
- appgate/state.py
- appgate/types.py
- tests/test_state.py
- tests/utils.py
We were not using the entities added in k8s when resolving dependencies.
> Fix bug when resolving entity dependencies

- appgate/openapi/parser.py
- tests/resources/test_entity.yaml
- tests/test_entities.py
- tests/utils.py
* `peerInterface` in Appliance 
* `displayName` in Entitlements
> [SA-18359] Return normal AttribMaker if the attrib is deprecated but required

- appgate/__main__.py
- appgate/appgate.py
- appgate/client.py
We were creating a new one every time we were entering the loop
This PR tries to reuse it as much as possible (it implements support for renewal of tokens)
> Reuse appgate client

- appgate/__main__.py
- appgate/appgate.py
- appgate/client.py
- appgate/openapi/openapi.py
- appgate/state.py
- appgate/syncer/git.py
- appgate/syncer/operator.py
- appgate/types.py
This way all the operators have the same logic and share code
> Use AppgatePlan for git operator

- appgate/__main__.py
- appgate/appgate.py
- appgate/attrs.py
- appgate/client.py
- appgate/openapi/openapi.py
- appgate/openapi/parser.py
- appgate/openapi/types.py
- appgate/state.py
- appgate/syncer/git.py
- appgate/syncer/operator.py
- appgate/types.py
- tests/resources/test_entity.yaml
- tests/test_appgatesecrets.py
- tests/test_entities.py
- tests/test_git.py
- tests/test_state.py
- tests/utils.py
Save id as metadata (annotation) in k8s and read it from there as well
> Propagate uuids

- appgate/client.py
- k8s/operator/templates/rbac.yaml
Some fixes
- reverse operator needs to be able to delete entities
- when modifying an entity in k8s we were using wrong key to get the name of the entity
> Some bug fixes

- appgate/syncer/git.py
* Build ssh command with shlex to prevent command injection
> Use shlex to build ssh command

- Makefile
- docker/Dockerfile
- docker/Dockerfile-build
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
> Update python to 3.11

- .github/workflows/build.yml
- renovate.json
> Bump to python 3.11

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
> Bump chart version to 0.2.12

- appgate/appgate.py
- appgate/syncer/git.py
- appgate/syncer/operator.py
- appgate/types.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/git-operator-deployment.yaml
- k8s/operator/values.yaml
> Custom paths

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/rbac.yaml
> Fix bug in chart

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/git-operator-deployment.yaml
- k8s/operator/templates/sdp-operator-deployment.yaml
- k8s/operator/values.yaml
> Add support for custom annotations

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/git-operator-deployment.yaml
- k8s/operator/templates/sdp-operator-deployment.yaml
- k8s/operator/values.yaml
> Add support for annotations in template as well

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/git-operator-deployment.yaml
- k8s/operator/values.yaml
> Add support to specify repository form in helm chart

- appgate/types.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- Fix bug when retrieving tags for singleton objects
> Fix bug in retrieval of tags for singleton entities

- appgate/state.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
Expected vs Current entity output should be debug
> Adjust log level
