- appgate/appgate.py
- appgate/state.py
Applies the plan in topological order. As it's computed by the openapi specification parser.
Fixes #57
> Iterate over the entities in topological order when applying plan

- README.org
- appgate/__main__.py
- appgate/appgate.py
- appgate/client.py
- appgate/types.py
- manifests/01-config.yaml
- manifests/02-appgate-operator.yaml
Self signed certificates can be now validated using:
- argument `--cafile file`
- environment variable `APPGATE_OPERATOR_CAFILE`
This is only used if `APPGATE_OPERATOR_NO_VERIFY` is not equal to 1.
Example usage:
`python3 -m appgate --spec-directory api_specs/v13/ dump-entities --cafile Appgate_SDP_envy-172-17-124-1.devops_CA.pem`
`APPGATE_OPERATOR_CACERT="$(cat Appgate_SDP_envy-172-17-124-1.devops_CA.pem|base64 -w0)" python3 -m appgate --spec-directory api_specs/v13/ dump-entities`
> Add support for custom certificates

- api_specs/v12/appliance_customization.yml
- api_specs/v12/ca.yml
- api_specs/v12/device_script.yml
- api_specs/v12/site.yml
- api_specs/v13/appliance_customization.yml
- api_specs/v13/ca.yml
- api_specs/v13/device_script.yml
- api_specs/v13/entitlement.yml
- api_specs/v13/site.yml
- appgate/openapi/parser.py
- appgate/openapi/types.py
- tests/resources/test_entity.yaml
- tests/test_entities.py
We had some cases where te `format` field was defined as a dictionary but the
standard requires a string there.
Also removed the need for `x-name`. Now when a field with a conflicting name is found we will try to make it compatible while keeping the original name for serialization/deserialization
> Make `format` field a string always in the openapi spec

- appgate/attrs.py
- appgate/state.py
- appgate/types.py
- examples/v13/administrativerole.yaml
- examples/v13/adminmfasettings.yaml
- examples/v13/appliancecustomization.yaml
- examples/v13/appliances.yaml
- examples/v13/clientconnection.yaml
- examples/v13/condition.yaml
- examples/v13/criteriascripts.yaml
- examples/v13/devicescript.yaml
- examples/v13/entitlement.yaml
- examples/v13/entitlementscript.yaml
- examples/v13/globalsettings.yaml
- examples/v13/identityprovider.yaml
- examples/v13/ippool.yaml
- examples/v13/localusers.yaml
- examples/v13/mfaprovider.yaml
- examples/v13/policy.yaml
- examples/v13/ringfencerule.yaml
- examples/v13/site.yaml
- examples/v13/trustedcertificates.yaml
We removed at some point the metadata.name from the CRD entities, this PR gives them back.
> Fix the examples we provide

- README.org
- appgate/appgate.py
The `APPGATE_OPERATOR_CACERT` can have a certificate in 2 formats:
- a raw string containing the PEM certificate :: `APPGATE_OPERATOR_CACERT=$(cat cert.ca)`
- a string containing the PEM encoded as bas64 :: `APPGATE_OPERATOR_CACERT=$(cat cert.ca|base64 -w 0)`
When using k8s might be easier to use the second format.
> Add support for PEM certs as strings and encoded in base64

- README.org
- appgate/__main__.py
- appgate/appgate.py
- appgate/attrs.py
- appgate/client.py
- appgate/openapi/types.py
- appgate/state.py
- examples/v13/administrativerole.yaml
- examples/v13/adminmfasettings.yaml
- examples/v13/appliancecustomization.yaml
- examples/v13/appliances.yaml
- examples/v13/clientconnection.yaml
- examples/v13/condition.yaml
- examples/v13/criteriascripts.yaml
- examples/v13/devicescript.yaml
- examples/v13/entitlement.yaml
- examples/v13/entitlementscript.yaml
- examples/v13/globalsettings.yaml
- examples/v13/identityprovider.yaml
- examples/v13/ippool.yaml
- examples/v13/localusers.yaml
- examples/v13/mfaprovider.yaml
- examples/v13/policy.yaml
- examples/v13/ringfencerule.yaml
- examples/v13/site.yaml
- examples/v13/trustedcertificates.yaml
- tests/test_appgatesecrets.py
- tests/test_entities.py
Adds a new cli command that allows to validate a set of entities against a specific version of the API:
```
root@6abe60fb7bcf:/project# python -m appgate --spec-dir api_specs/v14 validate-entities examples/v13
- Appliance::controller-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
- Appliance::gateway-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
- DeviceScript::fooscript: OK.
- TrustedCertificate::test-vsphere: OK.
- EntitlementScript::hello: OK.
- AdminMfaSettings::adminmfasettings: OK.
- ClientConnection::clientconnection: OK.
- LocalUser::bobbytables: OK.
- Condition::always: OK.
- IpPool::simple-setup-ipv6: OK.
- IpPool::default-pool-v6: OK.
- IpPool::simple-setup-ipv4: OK.
- IpPool::default-pool-v4: OK.
- IdentityProvider::connector: OK.
- IdentityProvider::local: OK.
- …
```
> Add entity-validator cli

- appgate/appgate.py
- appgate/client.py
- appgate/types.py
Continue defaulting to local.
Closes https://github.com/appgate/sdp-operator/issues/101.
> Add support for setting provider via APPGATE_OPERATOR_PROVIDER env var

- README.org
- appgate/__main__.py
- appgate/appgate.py
- appgate/client.py
- appgate/state.py
- appgate/types.py
It can be set via the new `APPGATE_OPERATOR_DEVICE_ID` environment variable.
If it is not set the operator will attempt to read it from the metadata config map where we currently store entity generations.
If it is not set there either it will generate a new device id and store it inside the config map.
Closes GH-71.
Closes GH-102.
> Add ability to set and persist device id

- requirements.txt
There is a dependabot alert on the version we are currently using.
> Bump aiohttp to 3.8.1

- appgate/bytes.py
- appgate/logger.py
- appgate/openapi/attribmaker.py
- appgate/openapi/parser.py
- appgate/openapi/types.py
- appgate/secrets.py
- tests/resources/test_entity.yaml
- tests/test_entities.py
- tests/utils.py
Fields defined as nullable will be of type `Optional[baseType]` while if they are not nullable the type will be `baseType` and a default factory method will be assigned
> Add support for nullable attribute in Openspec API

- appgate/logger.py
`logging.basicConfig` affects the root logger from which all other loggers derive.
This causes unrelated loggers from imported libraries to logwithout us explicitely enabling it, like `charset_noramlizer`.
> Set up appgate-operator logger explictly

- appgate/appgate.py
- appgate/attrs.py
- appgate/openapi/types.py
- appgate/types.py
- tests/test_appgatesecrets.py
Example log now (when failing to parse an entity with PEM):
```
2022-01-07 11:53:48,564 [ERROR] [trustedcertificates/sdp-demo] Unable to parse event with name Test Cert of type TrustedCertificate
2022-01-07 11:53:48,564 [ERROR] [trustedcertificates/sdp-demo]    !!! Error message: Unable to load PEM file. See https://cryptography.io/en/latest/faq.html#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidLength)
Path: .
2022-01-07 11:53:48,565 [ERROR] [trustedcertificates/sdp-demo]    !!! Error when loading from: PlatformType.K8S
2022-01-07 11:53:48,565 [ERROR] [trustedcertificates/sdp-demo]    !!! Error when loading type: TrustedCertificate
2022-01-07 11:53:48,565 [ERROR] [trustedcertificates/sdp-demo]    !!! Error when loading value: {'name': 'Test Cert', 'pem': '-----BEGIN …
```
> Make the operator to fail when there are erros parsing k8s entities

- requirements-build.txt
Upgrade black to 22.3.0 
https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
```
root@29c1a1c82f58:/build# black --check --diff appgate tests
Traceback (most recent call last):
File "/usr/local/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/usr/local/lib/python3.9/site-packages/black/__init__.py", line 1372, in patched_main
patch_click()
File "/usr/local/lib/python3.9/site-packages/black/__init__.py", line 1358, in patch_click
from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/usr/local/lib/python3.9/site-packages/click/__init__.py)
root@29c1a1c82f58:/build# 
exit
make: *** [docker-shell] Error 1
```
> Upgrade black to 22.3.0 for _unicodefun import error

- appgate/attrs.py
- appgate/discriminator.py
- appgate/openapi/parser.py
- tests/resources/crd/v12/identityprovider.yaml
- tests/resources/crd/v13/identityprovider.yaml
- tests/resources/crd/v14/identityprovider.yaml
- tests/resources/crd/v15/identityprovider.yaml
- tests/resources/crd/v16/identityprovider.yaml
- tests/resources/test_entity.yaml
- tests/resources/v12/identity_providers.yaml
- tests/resources/v16/identity_provider.yml
- tests/test_entities.py
- tests/test_state.py
- tests/utils.py
Add the ability to parse `discriminator` attributes to support IdentityProvider entity. 
When parsing an entity using discriminator, the parent entity (e.g. IdentityProvider) contains all attributes of its children and it keeps a mapping of resolved child entities (e.g. `IdentityProvider_Saml`, `IdentityProvider_Ldap`). User can continue to use the IdentityProvider CR to configure an identity provider on SDP. 
The validation for the fields are done by `DiscriminatorAttribMaker`. When you load a IdentityProvider with type=Saml, it makes sure that all fields required for type=Saml is present in the requested entity.
> Support IdentityProvider in the SDP Operator

- k8s/crd/Chart.yaml
Library charts are not deployable.
> Convert CRD chart into application chart

- k8s/chart/templates/rbac.yaml
Operator errors out because it hits permissions issues when it tries to watch the resources. The resources now have versions appended to their names. Apply that change to the RBAC.
> Append versions to the resources to watch in RBAC

- README.md
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/deployment.yaml
- k8s/operator/values.schema.json
- k8s/operator/values.yaml
Pass tag as array in values.yaml and join them into a comma-separated string before passing it to env
The following yaml 
```
targetTags:
- targetFoo
excludeTags:
- excludeFoo
- excludeBar
builtinTags:
- builtin
``` 
will be passed to the environment as 
```
root@sdp-operator-65c56c689-q4n2g:~# env | grep TAGS
APPGATE_OPERATOR_BUILTIN_TAGS=builtin
APPGATE_OPERATOR_TARGET_TAGS=targetFoo
APPGATE_OPERATOR_EXCLUDE_TAGS=excludeFoo,excludeBar
```
> Allow tags as array in values.yaml

- appgate/attrs.py
- k8s/crd/templates/v17.yaml
- requirements-build.txt
- requirements.txt
- tests/resources/crd/v17/policy.yaml
* Update packages to their latest available
* I skipped updating typedload to 2.18 because I hit an issue while testing. Will take a look at when I have more time. 
Tested the sdp-operator deployment on my local cluster
> Update python packages to their latest available

- Makefile
- docker/Dockerfile
- k8s/operator/templates/deployment.yaml
When you directly run the SDP operator image, (e.g. `docker run sdp-operator api-info`), it hits a FileNotFound error when looking for the API specification. Fix the location of the API specs in the Dockerfile and adjust the helm chart.
> Dump API specs into /root instead of /root/api_specs

- requirements.txt
Run `pip-compile` to update some packages, particular `certifi` for CVE-2022-23491
> Update certifi to 2022.12.07 version for CVE-2022-23491

- README.md
3 fixes:
- Added `generic` to the secrets creation. `--from-literal` can only be done with a generic secret.
- Fixed type of `-` to `=`
- Removed ` ` after a `\`, as it caused the copied command to split into two separate commands.
> Fixed a few small bugs with the README.md

- k8s/operator/templates/_helpers.tpl
- k8s/operator/templates/rbac.yaml
It causes conflicts when deploying the chart in the same ns twice
> Don't reuse the name in rbac in case the same NS is used for deployment

- appgate/customloaders.py
- appgate/files.py
- appgate/openapi/parser.py
- appgate/openapi/types.py
- appgate/openapi/utils.py
- appgate/secrets.py
- appgate/syncer/git.py
- appgate/types.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- tests/test_appgatesecrets.py
- tests/test_entities.py
- tests/test_state.py
Added upload instructions to entity that needs to be loaded from an external source. 
When computing the commit message for each entity, we check if `appgate_metadata["url_file_path"] is set. If it is set, print instructions specifying what path to upload the file/secret contents of the external storage. 
I'm using `url_file_path()` which is also used by the loader to figure out what URL to fetch the contents.
> Generate upload instructions in the PR for secrets and bytes

- Makefile
- appgate/openapi/types.py
- k8s/crd/Chart.yaml
- k8s/crd/templates/v16.yaml
- k8s/crd/templates/v17.yaml
- k8s/crd/templates/v18.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/rbac.yaml
- tests/resources/entity/v18/clientprofile.yaml
Add `ClientProfile` as an entity. ClientConnection was deprecated in favor of ClientProfile from v17.
I added a make command to ease the CRD helm chart generation. It runs dump-crd from the docker image and prepends/appends the necessary helm if statement.
> Add ClientProfile as a supported entity

- renovate.json
> Add constraints to run python 3.10 pip-compile

- docker/Dockerfile
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- requirements.in
- requirements.txt
Address the following policy violation:
- Fixable CVE-2022-40897 (CVSS 5.9) (severity Moderate) found in component 'setuptools' (version 65.5.0), resolved by version 65.5.1
```
appgate@sdp-operator-sdp-6d6d5655b5-6xhvd:/appgate$ python3 -c "import setuptools; print(setuptools.__version__)"
65.5.1
```
- Fixable CVE-2023-45803 (CVSS 4.2) (severity Moderate) found in component 'urllib3' (version 1.26.17), resolved by version 1.26.18
```
$ cat requirements.txt | grep urllib3
urllib3==1.26.18
```
- Image includes component 'curl' (version 7.88.1-10+deb12u4)
```
appgate@sdp-operator-sdp-6d6d5655b5-6xhvd:/appgate$ curl
bash: curl: command not found
```
- Image includes component 'apt' (version 2.6.1)
```
appgate@sdp-operator-sdp-6d6d5655b5-6xhvd:/appgate$ apt-get
bash: apt-get: command not found …
```
> Harden sdp-operator image

- docker/Dockerfile
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- requirements.in
- requirements.txt
- Bump cryptography to 41.0.7
- Bump libgnutls to 3.7.9-2+deb12u1
> Upgrade package version to address vulnerabilities

- appgate/state.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
We need to ignore entities that have been filtered out since there is no classes for them
> Don't reference entities that are filtered when resolving the ordering

- appgate/syncer/git.py
- appgate/syncer/operator.py
- appgate/types.py
- docker/Dockerfile
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- k8s/operator/templates/git-operator-deployment.yaml
- k8s/operator/values.yaml
Overriding `.Values.sdp.gitOperator.git.sshKnownHostsFile` will instruct the Git Operator to write the SSH fingerprints for Github/GitLab into the path specified in this value. If the value is set, `-o UserKnownFile=<path>` is appended to the git ssh command when cloning. If the value is not provided, it will use the default known file (`/home/appgate/.ssh/known_hosts`)
> [SA-23422] Add ability to configure path for known host file

- appgate/openapi/openapi.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
v20 API response contains `totalCount` as a new property. Our logic to determine if an entity is a singleton was checking if the response contains the properties for a non-singleton entity. Created a version-dependent list of properties.
> v20 added 'totalCount' as a  property for non-singleton entity

- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
- requirements.in
- requirements.txt
Bump the following packages:
- typedload 2.27
- cryptography 42.0.5
- gitpython 3.1.43
- aiohttp 3.9.5
> Bump packages to mitigate vulnerabilities

- appgate/attrs.py
- k8s/crd/Chart.yaml
- k8s/operator/Chart.yaml
Similar to `notes`, description should be an empty string, not null
> Default empty 'description' in Sites to empty string, not null
